### ISSUE TITLE
inga statuskoder

### ISSUE THREAD

**Issue by Guepen** [lr222gw/lr222gw_Webbramwek#10]
du anger inga statuskoder i dina actions. När man t.ex. skapar en resurs vill ge statusen created vilket kan göras på följande sätt:

 render json: someCreatedResource, status: :created

Det finns så klart många fler statuskoder men de som kan vara värda att undersöka kan vara: no_content, ok, unprocessable_entity, not_found

**Comment by lr222gw** [comment]
tack ska kika mera på detta :)
