### ISSUE TITLE
Google geocoder failing due to over_query_limit

### ISSUE THREAD

**Issue by Guepen** [lr222gw/lr222gw_Webbramwek#3]
Hej! 

När jag kör din seed får jag Google geocoder failing due to over_query_limit. Detta beror på att det görs för många anrop på kort tid eftersom du har ganska mycket seed data. Jag kommenterade ut lite seeds och då fungerade det! Kanske du inte behöver använda geocoder i din seed utan köra på hårdkodade positioner.

**Comment by lr222gw** [comment]
Fixat! Detta var en dum miss av mig, hehe :) 
Såg felmeddelandet precis i slutet och trodde det berodde på att jag hade testat för mycket mot googles servrar... :+1:
