### ISSUE TITLE
ingen felhantering för API:et

### ISSUE THREAD

**Issue by Guepen** [lr222gw/lr222gw_Webbramwek#8]
Det saknas för felhantering i API:et. Om man försöker hämta en resurs som inte finns får man röd-ful sida. Du borde lägga in rescuce där du i koden gör en model.find(params[:id]) kan du göra något liknande:  
rescue ActiveRecord::RecordNotFound
    # tell the user what went wrong and give statuscode 404
    render json: "modelName/#{params[:id]} could not be found", status: :not_found
  end

Du verkar inte heller ha någon felhantering ifall det inte går bra att spara en resurs

**Comment by lr222gw** [comment]
Felhantering för de skrivna testen är fixade
