### ISSUE TITLE
Strong parameters

### ISSUE THREAD

**Issue by Guepen** [lr222gw/lr222gw_Webbramwek#9]
Du använder dig inte av strong parameters när du skapar/uppdaterar en resurs vilket är ganska stor säkerhetsrisk eftersom man då kan skicka med vilka parametrar som helst.

T.ex i din tagsController skulle du kunna göra ungefär så här: 

 def create
      tag = Tag.new(tag_params)

```
 if tag.save
  render json: tag, status: :created
else
  #felhantering om det inte går att spara
  render json: tag.errors, status: :unprocessable_entity
end
```

 end

def tag_params
    params.permit(:name)
  end

**Comment by lr222gw** [comment]
Fixat!
